apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mariadb-volume-claim
  labels:
    app: nextcloud-mariadb
spec:
  storageClassName: hynix-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi