---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgAM58IDQhB3y/OkW0y4iFvk3iTzgCk6kiWP9IjyJK+/72fP2f4HVSiMmKwpMokeyO8KGp34G/dB7hDXaNVslYOSZWd/Xyw8WZ3YeXhGpRT18T9E2vMShEygziG7/c7rbMh7MQ8mxqfkxeMVy8CA9s6ZMNO4ASEFB6DkrtM3fARI8aZA8BDTwqND/NnYJEdGSfGF1vUjXKq5sB3aOTAfzNFdfUdrBSzc0N5EAzgibLlbHuui3FgI1EfVXvAUjQ+IwRCTHT7h2aYkK+pMct84wPYheKNcHqhZCF6Pr14ZLb1xgGBwKl6771GFmvQ7hL+6UblQU5U3OMuu8VoEWrOmbv4md52hj6igsVO2BtfXVXdUF7C9+jWOSD7BsBsQvHkcdBeEil0JTxFTN1BKalyV1Ld9OWLWmJUzlOdNfc7XphjTn+6DbkJ3EylvIT57GCFJPmcuL0ATr7bS5jUzV0MWggEzo7va/3eDRQ5deqYcjm8XiXGGvkKFdxF7nQA5PAu5FHTMq30DqQBELYAT8LTJfiQU2/s8OLZhSeUTVG2FCOiznf8Enr1Ks79HT8dTXXW+Ak6vrodNFvNhba+XRcG40oyQ5eqO29C0AjFMikNS1LQiPOqk8awpVbSw5kxsi9n61yfl5siZZfAqWwkF0WKjqGHJbNYcLiXeK2AY9MCB75vW6sho6rBVPLWAP8wUs9d8k7gUuQnPF3wsW1Yw8F6BkMla7kf1ftxbxFS2XtsfHPo8l46y
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud
