apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-volume-claim
  labels:
    app: nextcloud
spec:
  storageClassName: nextcloud-hynix-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi